data:
  shfe:
    broker_id: '9999'
    gateway: CTP
    host: 180.168.146.187
    password: your_password
    port: 10101
    user: your_username
event_persist_path: events.jsonl
logging:
  file: trading.log
  level: INFO
market_data:
  auto_subscribe: true
  cache_size: 1000
  main_contract: au2512
  redis:
    db: 0
    host: localhost
    port: 6379
risk:
  max_daily_loss: 10000
  max_position_risk: 0.1
  stop_loss_pct: 0.02
strategies:
  shfe_quant:
    config:
      add_interval: 50
      avg_loss: 1.0
      avg_win: 1.5
      ma_long: 20
      ma_short: 5
      martingale_multiplier: 2.0
      max_position: 5
      position_mode: fixed
      position_multiplier: 1.0
      position_size: 1
      risk_factor: 0.02
      rsi_overbought: 70
      rsi_oversold: 30
      rsi_period: 14
      stop_loss: 0.05
      strategy_type: trend
      symbol: au2507
      take_profit: 0.08
      win_rate: 0.6
    enabled: true
    type: shfe_quant
  spread_arbitrage:
    config:
      max_position: 1000
      mt5_symbol: XAUUSD
      shfe_symbol: AU9999
      spread_threshold: 0.5
    enabled: false
    type: spread_arbitrage
